import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './_sections/providers';
import { getMessages, unstable_setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import SideBar from './_sections/side-bar';
import Header from './_sections/header';
import { auth } from '@/auth';
import 'react-toastify/dist/ReactToastify.css';
import { HMSRoomProvider } from '@100mslive/react-sdk';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Kodigo',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'de' }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  unstable_setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html className="dark" lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <div className="m-auto flex w-full bg-white">
              <SideBar />
              <div className="h-screen w-full grow overflow-auto px-8">
                <div className="flex h-full w-full flex-col gap-8">
                  <Header />
                  {children}
                </div>
              </div>
            </div>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
